server:
  port: 12500
spring:
  application:
    name: panel-client-monitor

  data:
    redis:
      port: 6379
      host: localhost
      database: 4
      timeout: 2s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 2
