server:
  port: 8080
spring:
  application:
    name: panel-center-server
  data:
    redis:
      port: 6379
      host: localhost
      database: 4
      timeout: 2s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 2
qy:
  panel:
    auth-key: 56ba28f0-159d-4832-aeff-6fd44d3baaae

sa-token:
  token-style: random-64  # token风格:随机64位字符串;
  token-name: token
  timeout: 10800
  active-timeout: -1
  is-log: true
  is-concurrent: false
  is-color-log: true