server:
  port: 8088
spring:
  application:
    name: panel-client-kubernetes
  data:
    redis:
      port: 6379
      host: localhost
      database: 4
      timeout: 2s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 2
  k8s:
    master-url: https://192.168.136.131:6443
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Inh2Zk9BSmhscmd2NERlaFdoeUV0YkR3YlBDcW5UTGJwT0ZvekNacTBNRVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJuYW1lc3BhY2UtY29udHJvbGxlci10b2tlbi1yeDg4MiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJuYW1lc3BhY2UtY29udHJvbGxlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImU2MDQ4ZTI3LWNlNzMtNGM5MS04ZTdmLWJkMzgwMzI2YWIyOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpuYW1lc3BhY2UtY29udHJvbGxlciJ9.X4lP513gTgnbmx7rbP7_TM4VoVcPjqGr36u9zPYV2FHtwVlsgp84XJizpsZQG2hyOnyqN33oa1kbAGHtFqU8nRKxSimt_dWbgFsO1uaoj4yDdQOTXbOl2wvZ2n_KLL8sSe3mSZRc5F55dWBHGtHAovEa3su6-GrU5KfQO17aNRTkuyeJLkRh8ohxowb7tKOD5TQR1AHq3qnkINAFPTLSjNK3vFHULypRKypZSKe4GvWenzWgQBzsgUxzX4tly1wMDtbErQWM4m5CK33a8Y8meFkhPExuv4jo7zXr-z9DdD5f2uE2O9q_LamhBgNwrlevbxSVNx-AUfw4xc4IE1803w
    trust-certs: true